version: "3.9"

services:
  registration_s:
    container_name: registerer
    hostname: reg
    build:
      context: ./Registerer
      dockerfile: Dockerfile
    env_file: .env
    ports:
     - 8000:8000
    networks:
      - ciao
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./logs:/logs

  peer_s:
    container_name: peer
    build:
      context: ./Peer
      dockerfile: Dockerfile
    networks:
      - ciao
    volumes:
      - ./logs:/logs
    depends_on:
      - registration_s

networks:
  ciao:
    name: ciao