version: "3.9"

services:
  registration_s:
    container_name: registerer
    hostname: registerer
    build:
      context: ./Registerer
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - mutual_exclusion_network
    volumes:
      - ./logs:/logs

  peer_s:
    deploy:
      replicas: 3
    build:
      context: ./Peer
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - mutual_exclusion_network
    volumes:
      - ./logs:/logs

networks:
  mutual_exclusion_network:
    name: network1234
