version: "3.9"

services:
  registration_s:
    container_name: registerer
    hostname: registerer
    build:
      context: .
      dockerfile: ./Dockerfiles/registration_docker
    env_file: .env
    networks:
      - mutual_exclusion_network
    volumes:
      - ./logs:/logs

  peer_s:
    build:
      context: .
      dockerfile: ./Dockerfiles/peer_docker
    env_file: .env
    networks:
      - mutual_exclusion_network
    volumes:
      - ./logs:/logs

networks:
  mutual_exclusion_network:
    name: network1234
